baseurl: https://hinger.netlify.app/
# title: Semba-blog
googleAnalytics: "G-ZXGMSGS13L"
languageCode: de
DefaultContentLanguage: en
paginate: '5'
theme: hugo-dpsg
Author:
  avatar: img/semba_cover.png
  bio: is data scientist and spatial analyst at the Nelson Mandela African Institution of Sciene and Technoloygy. He earned a degree in fisheries and Aquaculture and later Master in Marine Sciencs and PhD in Physical Oceanography both from the University of Dar es Salaam. He sourced skills in data science from informal education like Prof Google and Dr. Youtube
  name: Masumbuko Semba
Params:
  authorbox: yes
  copyright: Semba
  dateformat: 02.01.2006
  description: We Modernize Analytics with R!
  footer:
    right: The Golden Age of Data!
    text: '[Data for Decision Making](/imprint)'
  indexPager: yes
  logo:
    header: img/header_new.png
    image: img/myblog.png
    subtitle: Welcome to Our Analytic Gateway
    title: The Hinge
  mainSections:
    - post
    - blog
    - news
  opengraph: yes
  pager: yes
  post_meta:
    - author
    - date
    - categories
    - translations
  readmore: yes
  schema: yes
  sidebar:
    home: right
    list: left
    single: no
    widgets:
      - search
      - recent
      - categories
      - taglist
      - social
      - languages
  style:
    vars:
      highlightColor: '#003056'
  toc: no
  twitter_cards: yes
  widgets:
    recent_num: 5
    tags_counter: yes
menu:
  main:
    - identifier: start
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    # - identifier: dashboard
    #   name: Dashaboards
    #   url: /dashboard/
    #   weight: 3


markup:
  goldmark:
    renderer:
      unsafe: true
